# Generated by Django 5.1.4 on 2024-12-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_id_alter_patient_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
