# Generated by Django 5.1.4 on 2024-12-08 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_id_alter_doctor_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
